config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'senha', confirmation: 'verificacao', unlock: 'desbloquear', registration: 'registro', sign_up: 'cadastro' }
  get 'pages/home'
  root to: "pages#home"
  resources :equivalences
  resources :course_subjects
  resources :presences
  resources :subscriptions
  resources :users
  resources :lessons
  resources :classrooms
  resources :subjects
  resources :periods
  resources :students
  resources :courses
  resources :professors
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user
      if user.standard?
        cannot :index, User
        can [:read, :update, :destroy, :edit], User, id: user.id
      elsif user.admin?
        can :manage, :all
      else
        cannot :manage, :all
      end
    else
      can [:index, :show, :read], [Department, Subject, Professor, Course]
    end
    
    

    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :subject
  belongs_to :professor
  belongs_to :period
  has_many :lessons
  has_many :subscriptions
  has_many :students, through: :subscriptions
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :course_subjects
  has_many :subjects, through: :course_subjects
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :professors
    has_many :courses
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :equivalent_subject, class_name:'Subject'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  has_many :presences
  has_many :students, through: :presences
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :lesson
  belongs_to :student
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user, optional: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :subscriptions
  has_many :students, through: :subscriptions
  has_many :presences
  has_many :lessons, through: :presences
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true
  has_many :classrooms
  has_many :course_subjects
  has_many :courses, through: :course_subjects
  has_many :equivalences
  has_many :equivalent_subjects, through: :equivalences, source: :equivalent_subject
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :professor
    validates :name, presence: true
    mount_uploader :photo, PhotoUploader


    enum kind: {
      standard: 0,
      admin: 1,
      professor: 2,
      diretor: 3,
    }
    private
      def must_be_above_18
        if age < 18
          error.add('base', "Precisa ter 18 anos ou mais")
        end
      end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:department_id, :name)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def user_kind_options
        [['Administrador', :admin], ["Padrão", :standard]]
    end
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Departamento" %>
    <%= form.collection_select(:department_id, Department.all, :id, :name, {:selected => @subject.department_id }) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.department.name %></td>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <% if can? :edit, @subject %>
          <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <% end %>
        <% if can? :destroy, @subject %>
          <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @subject.department.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>
<% if can? :edit, @subject %>
  <%= link_to 'Edit', edit_subject_path(@subject) %> |
<% end %>
<%= link_to 'Back', subjects_path %>