config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'senha', confirmation: 'verificacao', unlock: 'desbloquear', registration: 'registro', sign_up: 'cadastro' }
  get 'pages/home'
  root to: "pages#home"
  resources :equivalences
  resources :course_subjects
  resources :presences
  resources :subscriptions
  resources :users
  resources :lessons
  resources :classrooms
  resources :subjects
  resources :periods
  resources :students
  resources :courses
  resources :professors
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user
      if user.standard?
        cannot :index, User
        can [:read, :update, :destroy, :edit], User, id: user.id
      elsif user.admin?
        can :manage, :all
      else
        cannot :manage, :all
      end
    else
      can [:index, :show, :read], [Department, Subject, Professor, Course]
    end
    
    

    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :subject
  belongs_to :professor
  belongs_to :period
  has_many :lessons
  has_many :subscriptions
  has_many :students, through: :subscriptions
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :course_subjects
  has_many :subjects, through: :course_subjects
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :professors
    has_many :courses
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :equivalent_subject, class_name:'Subject'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  has_many :presences
  has_many :students, through: :presences
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :lesson
  belongs_to :student
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user, optional: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :subscriptions
  has_many :students, through: :subscriptions
  has_many :presences
  has_many :lessons, through: :presences
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true
  has_many :classrooms
  has_many :course_subjects
  has_many :courses, through: :course_subjects
  has_many :equivalences
  has_many :equivalent_subjects, through: :equivalences, source: :equivalent_subject
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :professor
    validates :name, presence: true
    mount_uploader :photo, PhotoUploader


    enum kind: {
      standard: 0,
      admin: 1,
      professor: 2,
      diretor: 3,
    }
    private
      def must_be_above_18
        if age < 18
          error.add('base', "Precisa ter 18 anos ou mais")
        end
      end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def user_kind_options
        [['Administrador', :admin], ["Padrão", :standard]]
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaculdadeBack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete%> |
      <%= link_to 'Meu Perfil', user_path(current_user.id)%> |
    <% else %>
      <%= link_to 'Logar', user_session_path %> |
    <% end %>
    <%= link_to 'Deparmento', departments_path%> |
    <%= link_to 'Curso', courses_path%> |
    <% if can? :read, Professor %>
      <%= link_to 'Professor', professors_path%> |
    <% end %>
    <% if can? :show, Student%>
      <%= link_to 'Estudantes', students_path%> |
    <% end %>
    <%= link_to 'Matérias', subjects_path%> |
    <% if can? :show, Lesson%>
      <%= link_to 'Aulas', lessons_path%> |
    <% end %>
    <% if can? :show, Classroom%>
      <%= link_to 'Turmas', classrooms_path%>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if !user_signed_in?%>
    <%= link_to "login", new_user_session_path %>
<% end %>